### ISSUE TITLE
Invalid return character or leading space in header: User-Agent

### ISSUE THREAD

**Issue by FrankenLab** [davidderus/pydebrid#6]
Hello again. New problem just began. I reinstalled my FreeBSD system, after reinstalling Pydebrid and re-entering my login credentials it tells me "Invalid return character or leading space in header: User-Agent". I also get the same error now with just "pydebrid -i".

Any ideas?

Thanks!

**Comment by davidderus** [comment]
Hi!

Thanks for the feedback.
I will look into it asap, it may be a change in Alldebrid's code or an updated dependency breaking something.

Can you please provide a screenshot or full terminal log of the error?

**Comment by FrankenLab** [comment]
It just a single line error. I type pydebrid -i, it gives the error and asks if I want to update my credentials, if I  say yes and re-enter them, I get the same error, if I say No, it just exits.

**Comment by FrankenLab** [comment]
It looks like the error comes from the requests module called from alldebrid.py. I'll keep looking and see if I can find any other clues.

**Comment by FrankenLab** [comment]
This comes from requests/utils.py: 

```
def check_header_validity(header):
    """Verifies that header value is a string which doesn't contain
    leading whitespace or return characters. This prevents unintended
    header injection.
    :param header: tuple, in the format (name, value).
    """
    name, value = header

    if isinstance(value, bytes):
        pat = _CLEAN_HEADER_REGEX_BYTE
    else:
        pat = _CLEAN_HEADER_REGEX_STR
    try:
        if not pat.match(value):
            raise InvalidHeader("Invalid return character or leading space in header: %s" % name)
    except TypeError:
        raise InvalidHeader("Header value %s must be of type str or bytes, "
                            "not %s" % (value, type(value)))
```

**Comment by FrankenLab** [comment]
In alldebrid.py the url has changed from:
`'rapidDebrid': ALLDEBRID_ROOT + '/service.php',`
to
`'rapidDebrid': ALLDEBRID_ROOT + '/service/',`

This doesn't fix the problem, just something I noticed.

Am I the only one that uses this program??  Its super useful for me, probably not many people know about it?

**Comment by FrankenLab** [comment]
Ok, I just found the problem. I changed the User Agent string found in alldebrid.py to:
`Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36`
Now it works. I don't know how to remake the package, so hopefully you'll have some time soon.

**Comment by davidderus** [comment]
Hi ProtoSD,

Thanks for your useful feedback. Maybe pydebrid does not have many users, but I'm glad to have at least one such helpful as you.

Using your informations I was able to patch pydebrid and publish the [1.0.9 release on Pypi](https://pypi.python.org/pypi/pydebrid/1.0.9).

You can now update your installation with `pip install --upgrade pydebrid`.
