### ISSUE TITLE
Why don't use Alldebrid API ?

### ISSUE THREAD

**Issue by mathieutu** [davidderus/pydebrid#9]
instead of standard UI ?

cf http://docs.alldebrid.com

**Comment by davidderus** [comment]
Hi,
I was not aware of any official API when I wrote pydebrid, back in 2015.

Now that you link me one, I may implement it in the future (at least for [Christopher](https://github.com/davidderus/christopher)).

Thanks for the tip!

**Comment by mathieutu** [comment]
Ok. FYI I'm making a php SDK for this api. This is quite simple, only get methods, no complexity.. ☺️

**Comment by mathieutu** [comment]
I didn't know about Christopher! Cool! I'm doing something in this way too just to be able to launch vlc on my raspberry pi directly from any undebrided links on my pc!
